import Head from "next/head";
import { NextPage } from "next";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title> Uye Ol </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-item"> Uye Ol </div>
    </>
  );
};

export default Register;
