import Head from "next/head";
import Image from "next/image";
import { GetServerSideProps, NextPage } from "next";
import Layout from "@/components/Layout";
import { wrapper } from "@/redux/store";
import { User } from "@/types";
import { setCurrentUser } from "@/redux/slices/auth";

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (context) => {
    const authToken = context.req.cookies?.token;

    if (authToken) {
      const authApiReq = await fetch(
        `http://${process.env.API_HOST}:${process.env.API_PORT}/api/auth/getTokenUser`,
        {
          method: "GET",
          headers: {
            Authorization: "Bearer " + authToken,
          },
        }
      );

      if (authApiReq.status == 200) {
        const currentUser = (await authApiReq.json()) as User;

        store.dispatch(setCurrentUser({ currentUser }));
      } else {
        const response = await fetch(
          `/api/auth/logout`
        );
        const data = await response.json();

        console.log(data);

        return {
          redirect: {
            permanent: false,
            destination: "/auth/login",
          },
          props: {},
        };
      }
    } else {
      return {
        redirect: {
          permanent: false,
          destination: "/auth/login",
        },
        props: {},
      };
    }

    return { props: {} };
  });

const Arrivals: NextPage = () => {
  return (
    <>
      <Head>
        <title>Genel - Mal Kabul</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-item"> Genel - Mal Kabul </div>
      </Layout>
    </>
  );
};

export default Arrivals;
